
volumes:
  data:

services:
  postgres:
    container_name: postgres-sql
    image: postgres:12
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: postgres
    volumes:
      - data:/var/lib/postgresql/data
    ports:
        - "5433:5432"
